version: '3'

services:
  mysqldb:
    networks:
      prod:
    hostname: mysqldb
    image: mysql:5.7_v1
    container_name: mysqldb
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysq1root!
      MYSQL_DATABASE: database_schema
      MYSQL_USER: nodeuser
      MYSQL_PASSWORD: nodeuser!
    volumes:
      - ./mysql/data:/var/lib/mysql

  nodejs:
    networks:
      prod:
    hostname: nodejs
    image: nodejs:v1
    container_name: nodejs
    build:
      context: ./nodejs
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      - NODEJS_API_PORT=8080

  nginx:
    networks:
      prod:
    hostname: nginx
    image: nginx:v1
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    environment:
     -  NODEJS_IP=nodejs
    depends_on:
      - nodejs
#    command: echo $(ping -c1 $NODEJS_IP | sed -nE 's/^PING[^(]+\(([^)]+)\).*/\1/p') nodejs >> /etc/hosts

networks:
  prod:
    driver: bridge
