version: '3'

services:
  mysqldb:
    image: mysql:5.7_v1
    container_name: mysqldb
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysq1root!
      MYSQL_DATABASE: database_schema
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysql_dump:/docker-entrypoint-initdb.d

  nodejs:
    image: nodejs:v1
    container_name: nodejs
    build:
      context: ./nodejs
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      - NODEJS_API_PORT=8080

  nginx:
    image: nginx:v1
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    environment:
     -  NODEJS_IP=nodejs
    depends_on:
      - nodejs
